name: Release

on: push

permissions:
  contents: write

jobs:
  push_to_registries:
    name: Push Docker image to multiple registries
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: build push spark
        uses: docker/build-push-action@v2
        with:
          context: ./spark
          file: spark/Dockerfile
          push: true
          tags: ttbb/spark:nake
          platforms: linux/amd64,linux/arm64
      - name: build push py learn
        uses: docker/build-push-action@v2
        with:
          context: ./py-learn
          file: py-learn/Dockerfile
          push: true
          tags: ttbb/spark:py-learn
          platforms: linux/amd64,linux/arm64
